//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoIpc2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inscripcion
    {
        public int InscriptionId { get; set; }
        public int TournamentId { get; set; }
        public int UserId { get; set; }
    
        public virtual Torneo Torneo { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
