//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoIpc2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partida
    {
        public int GameId { get; set; }
        public string GameType { get; set; }
        public string GameMode { get; set; }
        public string XmlRouteBoard { get; set; }
        public int Player1MovesNumber { get; set; }
        public int Player2MovesNumber { get; set; }
        public int Player1Points { get; set; }
        public int Player2Points { get; set; }
        public int Player1Time { get; set; }
        public int Player2Time { get; set; }
        public string Resultado { get; set; }
        public int HostColor { get; set; }
        public Nullable<int> ChampionId { get; set; }
        public int UserId { get; set; }
    
        public virtual Campeonato Campeonato { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
